# Site settings
author: Christopher Baptiste
title: Chris Baptiste's Blog
header-img: img/home-bg.png
email: chrisbaptiste83@gmail.com
copyright_name: Christopher Baptiste
description: > # this means to ignore newlines until "baseurl:"
  A Venture Into Software Development 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chrisbaptiste83

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
